<a href="https://colab.research.google.com/github/kaushikpatriot/DSA-Code/blob/main/DynamicProgramming.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Dynamic Programming and Memoization

###Longest Common Word - Naive Approach
Using Naive approach
1. Two words a and b having m and n characters respectively
2. For each character in a, we look for a matching character in b and if there is a matching character then we start looking for a sequence of matching characters from that place.
3. We take out the longest such word and is called the Longest Common word

Example: bisect and secret has "sec" as the longest common word (LCW)


In [ ]:
def LCW_naive(a,b):
  (m,n) = (len(a),len(b))
  (i,j,k, count, max) = (0, 0, 0, 0, 0)

  for i in range(m):
    flag = False
    while j < n:
      if a[i] == b[j]:
        j += 1
        count += 1
        #print (a[i])
        flag = True
        break
      else:
        if count > max:
          max = count
        count = 0
        j += 1
    if not flag:
      j = 0
  return max

a = "director"
b = "secretary"
print (LCW_naive(a,b))

2


##Longest Common Word - Inductive Approach - Dynamic


In [ ]:
def LCW(u,v):
  import numpy as np
  (m,n) = (len(u),len(v))
  lcw = np.zeros((m+1,n+1))
  maxlcw = 0

  for c in range(n-1,-1,-1):
    for r in range(m-1,-1,-1):
      if (u[r] == v[c]):
        lcw[r,c] = 1+ lcw[r+1,c+1]
      else:
        lcw[r,c] = 0
      if lcw[r,c] > maxlcw:
        maxlcw = lcw[r,c]
  print (lcw)
  return maxlcw

print (LCW("bisect","secret"))


[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [3. 0. 0. 0. 0. 0. 0.]
 [0. 2. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]
3.0


##Longest Common Subsequence - Dynamic

In [ ]:
def LCS(u,v):
  import numpy as np
  (m,n) = (len(u),len(v))
  lcs = np.zeros((m+1,n+1))
  maxlcs = 0

  for c in range(n-1,-1,-1):
    for r in range(m-1,-1,-1):
      if (u[r] == v[c]):
        lcs[r,c] = 1+ lcs[r+1,c+1]
      else:
        lcs[r,c] = max(lcs[r+1,c],lcs[r,c+1])
      if lcs[r,c] > maxlcs:
        maxlcs = lcs[r,c]
  print (lcs)
  return maxlcs

print (LCS("ABCBDABACD","BDCABADCD"))


[[7. 6. 6. 5. 4. 4. 3. 2. 1. 0.]
 [7. 6. 6. 5. 4. 3. 3. 2. 1. 0.]
 [7. 6. 6. 5. 4. 3. 3. 2. 1. 0.]
 [7. 6. 5. 5. 4. 3. 3. 2. 1. 0.]
 [6. 6. 5. 5. 4. 3. 3. 2. 1. 0.]
 [5. 5. 5. 5. 4. 3. 2. 2. 1. 0.]
 [4. 4. 4. 4. 4. 3. 2. 2. 1. 0.]
 [3. 3. 3. 3. 3. 3. 2. 2. 1. 0.]
 [2. 2. 2. 2. 2. 2. 2. 2. 1. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
7.0


##Edit Distance - Dynamic
Calculate the minimum steps required to transform from one string to another

In [ ]:
def ED(u,v):
  import numpy as np
  (m,n) = (len(u),len(v))
  ed = np.zeros((m+1,n+1))

  for i in range (m-1,-1,-1):
    ed[i,n] = m-i

  for j in range(n-1,-1,-1):
    ed[m,j] = n-j

  for c in range(n-1,-1,-1):
    for r in range(m-1,-1,-1):
      if (u[r] == v[c]):
        ed[r,c] = ed[r+1,c+1]
      else:
        ed[r,c] = 1 + min(ed[r+1,c+1],ed[r,c+1],ed[r+1,c])

  #print (ed)
  return ed[0,0]


s1 = 'abc'
s2 = 'efghik'
print (ED(s1,s2))



6.0


##Matrix Chain Multiplication - Dynamic
Approach:
1. Input is the dimensions of the matrices in order


In [ ]:
def C(dim):
  import numpy as np
  n = dim.shape[0]
  mcost = np.zeros((n,n))
  for i in range(n):
    mcost[i,i] = 0
  for x in range (1,n):
    for i in range (0,n-x):
      j = i+x
      mcost[i,j] = mcost[i,i] + mcost[i+1,j] + dim[i,0]*dim[i,1]*dim[j,1]
      for k in range(i+1,j+1):
        mcost[i,j] = min(mcost[i,j],mcost[i,k-1] + mcost[k,j] + dim[i,0]*dim[k,0]*dim[j,1])
  return mcost

import numpy as np
L = np.array([[4,10],[10,3],[3,12],[12,20],[20,7]])
print (C(L))


[[   0.  120.  264. 1080. 1344.]
 [   0.    0.  360. 1320. 1350.]
 [   0.    0.    0.  720. 1140.]
 [   0.    0.    0.    0. 1680.]
 [   0.    0.    0.    0.    0.]]


##GrPA1 - Construct Word Problem

In [ ]:
memo = {}
def constructWord(word, wordList):
    if word == '':
        return [[]]
    if word in memo.keys():
        return memo[word]
    totalwordlist = []
    for subword in wordList:
        if subword == word[:len(subword)]:
            subwordList = constructWord(word[len(subword):], wordList)
            totalwordlist.extend([[subword] + lst for lst in subwordList])
    memo[word] = totalwordlist
    return totalwordlist

word = 'apple'
wordList = ['ap','pple','app','apl','appl','le','ple']
print (constructWord(word, wordList))


[['ap', 'ple'], ['app', 'le']]


##GrPA 3 - Longest Decreasing Sequence


In [ ]:
def LDS(L):
  LDS = [1]*len(L)
  depList = [-1]*len(L)
  subSeq = []

  for i in range (len(L)-1,-1,-1):
    for j in range (len(L)-1,i,-1):
      if (L[i] > L[j]):
        if (1+LDS[j] >= LDS[i]):
          depList[i] = j
          LDS[i] = 1+LDS[j]
      #LDS[i] = max(LDS[i], 1 + LDS[j])

  #print (L)
  print (LDS)
  print (depList)
  mx = max(LDS)
  for i in range(len(LDS)):
    if LDS[i] == mx:
      subSeq.append(L[i])
      depIdx = depList[i]
      break
  for k in range(mx-1):
    subSeq.append(L[depIdx])
    depIdx = depList[depIdx]
  return subSeq


#L = [2,4,3,2,5,1]
L = [47, 20, 46, 96, 44, 58, 29, 12, 2, 86]
#L = [0,2,7,3,7,3,8,2,1,0]
print (LDS(L))

[6, 3, 5, 5, 4, 4, 3, 2, 1, 1]
[2, 7, 4, 4, 6, 6, 7, 8, -1, -1]
[47, 46, 44, 29, 12, 2]


In [ ]:
def nsum(n,L):
  if n == 0:
    return []
  if n < 0:
    return None
  for i in L:
    x = nsum(n-i,L)
    if x != None:
      return x + [i]
  return None

n = 27
L = [6,7,8,3,2]
print (nsum(n,L))

[3, 6, 6, 6, 6]


In [ ]:
def subsetSum(L,k):
  n = len(L)
  T = [[False for x in range (k+1)] for y in range (n+1)]
  for i in range (n+1):
    T[i][0] = True
  for i in range (1, n + 1):
    for j in range (1, k + 1):
      if L[i - 1] > j:
        T[i][j] = T[i - 1][j]
      else:
        T[i][j] = T[i-1][j] or T[i-1][j-L[i-1]]

  print (T)

#L = [2,3]
L = [2,3,4,5,6]
k = 11
subsetSum(L,k)

[[True, False, False, False, False, False, False, False, False, False, False, False], [True, False, True, False, False, False, False, False, False, False, False, False], [True, False, True, True, False, True, False, False, False, False, False, False], [True, False, True, True, True, True, True, True, False, True, False, False], [True, False, True, True, True, True, True, True, True, True, True, True], [True, False, True, True, True, True, True, True, True, True, True, True]]


## GrPA -2 Grid path problem

In [ ]:
def MaxCoinPath(M,x1,y1,x2,y2):
  path = [[0 for i in range(len(M[0]))] for j in range (len(M))]
  path[x1][y1] = M[x1][y1]
  for i in range(x1,len(M)):
    path[i][y1] = path[i-1][y1] + M[i][y1]

  for j in range(y1,len(M[0])):
    path[x1][j] = path[x1][j-1] +M[x1][j]

  for i in range (x1+1,x2+1):
    for j in range (y1+1,y2+1):
      path[i][j] = max(path[i-1][j],path[i][j-1]) + M[i][j]

  return (path[x2][y2])

M = [[2,1,3,2,5],[3,5,2,4,6],[7,6,1,3,2],[2,9,4,7,8],[1,4,5,11,3]]
(x1,y1) = (1,4)
(x2,y2) = (3,4)
print (MaxCoinPath(M,x1,y1,x2,y2))


16


##Knapsack Problem

In [ ]:
def MaxValue(items,W):
  n = len(items.keys())
  # Check for exceptions
  if n == 0 or W == 0:
    return

  # create an empty numpy array
  import numpy as np
  mat = np.zeros(shape=(n+1,W+1))

  # Fill the matrix row by row, starting from row 1
  for i in range (1, n+1):
    for j in range (1,W+1):
      if (items[i][0] > j):
        mat[i,j] = mat[i-1,j]
      else:
        mat[i,j] = max(mat[i-1,j], items[i][1] + mat[i-1,j-items[i][0]])

  # return the last cell of the matrix
  return int(mat[n,W])

W = 25
items = {1:(5,20), 2:(1,50), 3:(16,80), 4:(4,100), 5:(5,200),6:(4,150),7:(2,300),8:(6,120),9:(3,70),10:(6,40)}
print (MaxValue(items,W))

990


In [ ]:
def MaxValue(Items,W):
  (m,n) = (len(Items),W)
  c = []
  for i in range(m+1):
    row = []
    for j in range(n+1):
      row.append(0)
    c.append(row.copy())
  for i in range(1,m+1):
    for w in range(1,n+1):
      if Items[i][0] > w:
        c[i][w] = c[i-1][w]
      else:
        c[i][w] = max(c[i-1][w],Items[i][1]+c[i-1][w-Items[i][0]])
  return(int(c[m][n]))

W = 30
items = {1:(10,2), 2:(15,5), 3:(6,8), 4:(9,1)}
print (MaxValue(items,W))


[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 2, 2, 2, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 7, 7, 7, 7, 7, 7], [0, 0, 0, 0, 0, 0, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 10, 10, 10, 10, 10, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13], [0, 0, 0, 0, 0, 0, 8, 8, 8, 8, 8, 8, 8, 8, 8, 9, 10, 10, 10, 10, 10, 13, 13, 13, 13, 13, 13, 13, 13, 13, 14]]
14


##Activity with Max Profit - Scheduling

In [ ]:
def MaxProfit(Activity):
  # Sort Activities based on end time
  L = ([(k,i,j,l) for i,j,k,l in Activity])
  L.sort()
  L = (([(i,j,k,l) for k,i,j,l in L]))

  #Initialise a Profit list consisting of the number of Activities
  n = len(L)
  profit = [0] * (n)

  # Basecase - fill the profit for the last activity to happen
  profit[-1] = L[-1][3]

  # Populate the profit list
  for i in range(n-2, -1, -1):
    for j in range(n-1, i, -1):
      #Check if the activity at i is compatible with activity at j:
      if (L[i][2] > L[j][1]): # Incompatible activities
        #print('Incomp',L[i][0],L[j][0],profit[i],L[i][3])
        profit[i] = max(profit[i],L[i][3])
      else: # Compatible activities
        #print('Comp',L[i][0],L[j][0],profit[i],L[i][3],profit[j])
        profit[i] = max(profit[i],L[i][3] + profit[j])
  return max(profit)

Activity = [('A',0,2,22),('B',2,4,45),('C',3,7,26),('D',5,8,13)]
print (MaxProfit(Activity))

80
