<a href="https://colab.research.google.com/github/kaushikpatriot/DSA-Code/blob/main/GraphAlgos2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Single Source Shortest Path - Dijkstra's Algorithm##

In [ ]:
#Edges with positive weights
edges = [(0,1,10),(0,2,80),(1,0,10),(1,2,6),(1,4,20),(2,0,80),(2,3,70),(3,2,70),(4,1,20),(4,5,50),(4,6,5),(5,4,50),(5,6,10),(6,5,10)]
dim = 7

In [ ]:
#Edges with negative weights
edges = [(0,1,10),(0,7,8),(1,5,2),(2,1,1),(2,3,1),(3,4,3),(4,5,-1),(5,2,-2),(6,1,-4),(6,5,-1),(7,6,1)]
dim = 8

In [ ]:
#GA Edges
edges = [(0,1,-10),(1,2,-20),(2,3,-20)]
dim = 4

In [ ]:
#Adjacency Matrix
import numpy as np
Amat = np.zeros(shape=(dim,dim,2))
for (i,j,w) in edges:
    Amat[i,j,0] = 1
    Amat[i,j,1] = w
print(Amat)

[[[ 0.  0.]
  [ 1. 10.]
  [ 0.  0.]
  [ 0.  0.]
  [ 0.  0.]
  [ 0.  0.]
  [ 0.  0.]
  [ 1.  8.]]

 [[ 0.  0.]
  [ 0.  0.]
  [ 0.  0.]
  [ 0.  0.]
  [ 0.  0.]
  [ 1.  2.]
  [ 0.  0.]
  [ 0.  0.]]

 [[ 0.  0.]
  [ 1.  1.]
  [ 0.  0.]
  [ 1.  1.]
  [ 0.  0.]
  [ 0.  0.]
  [ 0.  0.]
  [ 0.  0.]]

 [[ 0.  0.]
  [ 0.  0.]
  [ 0.  0.]
  [ 0.  0.]
  [ 1.  3.]
  [ 0.  0.]
  [ 0.  0.]
  [ 0.  0.]]

 [[ 0.  0.]
  [ 0.  0.]
  [ 0.  0.]
  [ 0.  0.]
  [ 0.  0.]
  [ 1. -1.]
  [ 0.  0.]
  [ 0.  0.]]

 [[ 0.  0.]
  [ 0.  0.]
  [ 1. -2.]
  [ 0.  0.]
  [ 0.  0.]
  [ 0.  0.]
  [ 0.  0.]
  [ 0.  0.]]

 [[ 0.  0.]
  [ 1. -4.]
  [ 0.  0.]
  [ 0.  0.]
  [ 0.  0.]
  [ 1. -1.]
  [ 0.  0.]
  [ 0.  0.]]

 [[ 0.  0.]
  [ 0.  0.]
  [ 0.  0.]
  [ 0.  0.]
  [ 0.  0.]
  [ 0.  0.]
  [ 1.  1.]
  [ 0.  0.]]]


In [ ]:
#Adjacency List
Alist = {}
for i in range(dim):
  Alist[i] = []
for (i,j,k) in edges:
  Alist[i].append((j,k))

print (Alist)

{0: [(1, 1), (2, 8), (3, 1), (4, 4)], 1: [(2, 12), (3, 4), (4, 9), (0, 1)], 2: [(3, 7), (4, 3), (0, 8), (1, 12)], 3: [(4, 2), (0, 1), (1, 4), (2, 7)], 4: [(0, 4), (1, 9), (2, 3), (3, 2)]}


In [ ]:
Alist = {
    1:[(2,10),(8,8)],
    2:[(6,2)],
    3:[(2,1),(4,1)],
    4:[(5,3)],
    5:[(6,-1)],
    6:[(3,-2)],
    7:[(2,-4),(6,-1)],
    8:[(7,1)]
}

###Djikstra's approach - O(n^2):
1. A dictionary of estimated distance to each vertex from the single source is maintained and initialised with infinity(max distance)
2. The distance to the source vertex is set to zero
3. Iteratively, the vertex with the least distance is chosen. If more than one vertex has the same minimum distance, then a consistent logic is applied to choose a vertex. E.g. Minimum of vertices can be chosen
4. Once a vertex is visited, it is marked so. The distance to the connected vertices are updated as the minimum of the distance to the current vertex + the distance to the next vertex or the already updated distance of the next vertex
5. Negative weights are not permitted

Dijkstra can return:
1. Shortest path from a single source to any point
2. Longest route from a single source



In [ ]:
#Dijkstra's Algorithm with Adjacency Matrix
# Call the function with (Amat, source vertex)
def dijkstra_Amat(Amat,s):
# Infinity = the max value among all the the cells * rows + 1
  max = 0
  for i in range(len(Amat)):
    for j in range(len(Amat)):
      if (Amat[i][j][1] > max):
        max = Amat[i][j][1]
  infinity = max*len(Amat)+1
# For each vertex in Amat
# set visited = false and distance = infinity
  (visited,distance) = ({},{})
  for i in range(len(Amat)):
    visited[i] = False
    distance[i] = infinity
# Set distance for source vertex = 0
  distance[s] = 0
# For each vertex
  for i in range(len(Amat)):
#  find the list of vertices with least distance and not visited
    nextd = min([distance[d] for d in range(len(Amat))
                if not visited[d]])
    nextvlist = ([v for v in range(len(Amat))
              if not visited[v] and distance[v] == nextd])
    if (nextvlist==[]):
      break
#   find the least vertex from the above list
#   set that vertex to be visited
    nextv = min(nextvlist)
    visited[nextv] = True
#   for each neighbour of this the above vertex
#       set the distance to the minimum of (current distance, the distance of the source vertex + weight)
    for j in range(len(Amat)):
      if(Amat[nextv][j][0] == 1 and not visited[j]):
        distance[j] = min(distance[j],distance[nextv]+Amat[nextv][j][1])
# return distance
  return distance

dijkstra_Amat(Amat,0)

{0: 0, 1: 10, 2: 16, 3: 86, 4: 30, 5: 45, 6: 35}

In [ ]:
#Dijkstra's algorithm with adjacency list
# Call the function with (Amat, source vertex)
def dijkstra_Alist(Alist,s):
# Infinity = the max value among all the the cells * rows + 1
  max = 0
  for i in Alist:
    for j in Alist[i]:
      if (j[1]) > max:
        max = (j[1])
  infinity = max*len(Alist)+1
# For each vertex in Amat
# set visited = false and distance = infinity
  (visited,distance) = ({},{})
  for i in Alist:
    visited[i] = False
    distance[i] = infinity
# Set distance for source vertex = 0
  distance[s] = 0
# For each vertex
  for i in Alist:
#  find the list of vertices with least distance and not visited
    nextd = min([distance[d] for d in Alist
                if not visited[d]])
    nextvlist = ([v for v in Alist
              if not visited[v] and distance[v] == nextd])
    if (nextvlist==[]):
      break
#   find the least vertex from the above list
#   set that vertex to be visited
    nextv = min(nextvlist)
    visited[nextv] = True
#   for each neighbour of this the above vertex
#       set the distance to the minimum of (current distance, the distance of the source vertex + weight)
    for j,k in Alist[nextv]:
      if(not visited[j]):
        distance[j] = min(distance[j], distance[nextv]+k)
# return distance
  return distance

dijkstra_Alist(Alist,0)


{0: 0, 1: 10, 2: 16, 3: 86, 4: 30, 5: 45, 6: 35}

###Single Source Shortest Path - Bellman Ford Algorithm
1. Negative weights are permitted as long as there are no negative cycles (cycles with net negative weight)
2. Distances are updated to infinity
3. Set the distance to source to zero
4. Iteratively visit the vertex with least distance. If there are multiple vertices with the same minimum distance, choose the least of the vertices (there can be other strategies).
5. Update the distance to the associated vertices as the minimum of the current distance to the vertex or the new distance from the visted vertex and the edge weight
6. Unlike Djikstra's the process is repeated as many times as there are vertices, thus allowing for backward adjustment of distance based on the weight.

In [ ]:
# Bellman-Ford using Adjacency matrix
# Call the function with Amat and source
# Find infinity
# Initialise distance with infinity (visited not required to be kept track of in this algorithm)
# set distance of the source to zero
# Iteratively

def bellman_ford(Amat,s):
  # Infinity = the max value among all the the cells * rows + 1
  max = 0
  for i in range(len(Amat)):
    for j in range(len(Amat)):
      if (Amat[i][j][1] > max):
        max = Amat[i][j][1]
  infinity = max*len(Amat)+1
# For each vertex in Amat
# set visited = false and distance = infinity
  distance = {}
  for i in range(len(Amat)):
    distance[i] = infinity
# Set distance for source vertex = 0
  distance[s] = 0
  for i in range(len(Amat)):
    for u in range(len(Amat)):
      for v in range(len(Amat[0])):
        if (Amat[u][v][0] == 1):
          distance[v] = min(distance[v],distance[u] + Amat[u][v][1])
  return distance

print (bellman_ford(Amat,0))



{0: 0, 1: 5.0, 2: 5.0, 3: 6.0, 4: 9.0, 5: 7.0, 6: 9.0, 7: 8.0}


In [ ]:
# Bellman-Ford using Adjacency List
# Call the function with Alist and source
# Find infinity
# Initialise distance with infinity (visited not required to be kept track of in this algorithm)
# set distance of the source to zero
# Iteratively

def bellman_ford(Alist,s):
# Infinity = the max value among all the the cells * rows + 1
  max = 0
  for i in Alist:
    for j in Alist[i]:
      if (j[1]) > max:
        max = (j[1])
  infinity = max*len(Alist)+1
# For each vertex in Amat
# set visited = false and distance = infinity
  distance = {}
  for i in Alist:
    distance[i] = infinity
# Set distance for source vertex = 0
  distance[s] = 0
  for i in Alist:
    for u in Alist:
      for v,d in Alist[u]:
        distance[v] = min(distance[v],distance[u] + d)
  return distance

print (bellman_ford(Alist,0))

{0: 0, 1: 5, 2: 5, 3: 6, 4: 9, 5: 7, 6: 9, 7: 8}


##Minimum Cost Spanning Tree - Prim's Algorithm##

In [ ]:
#Edges for MCST - Prims
dedges = [(0,1,10),(0,3,18),(1,3,6),(3,4,70),(1,2,20),(2,4,8)]
edges = dedges + [(j,i,w) for i,j,w in dedges]
dim = 5

In [ ]:
#Edges for MCST - Kruskal
dedges = [(0,1,10),(0,2,18),(1,2,6),(1,4,20),(2,3,70),(4,5,10),(4,6,10),(5,6,5)]
edges = dedges + [(j,i,w) for i,j,w in dedges]
dim = 7

In [ ]:
#Edges for MCST - Kruskal
dedges = [(0,1,1),(0,2,8),(0,3,1),(0,4,4),(1,2,12),(1,3,4),(1,4,9),(2,3,7),(2,4,3),(3,4,2)]
edges = dedges + [(j,i,w) for i,j,w in dedges]
dim = 5

Strategy:

1. Start at vertex 0
2. Add the edge from there with the least cost to the tree
3. From the connected vertex above look for the edge with the least cost, that does not form a cycle and add that to that tree
4. Repeat 3 until all the edges are either added or ignored


In [ ]:
def prims(Alist):
  (visited, distance, TE) = ({}, {}, [])
  # Initialise
  infinity = 1 + max([d for i in Alist for v,d in Alist[i]])
  for i in Alist:
    visited[i], distance[i] = False, infinity

  visited[0] = True
  for v,d in Alist[0]:
    distance[v] = d

  for i in Alist.keys():
    (mindist,nextv) = (infinity, None)
    for u in Alist.keys():
      for (v,d) in Alist[u]:
        if visited[u] and (not visited[v]) and d < mindist:
          (mindist,nextv,nexte) = (d,v,(u,v))
    if nextv is None:
      break
    visited[nextv] = True
    TE.append(nexte)
    for v,d in Alist[nextv]:
      distance[v] = min(distance[v],d)
  return TE

print(prims(Alist))

[(0, 1), (0, 3), (3, 4), (4, 2)]


In [ ]:
def prims_algo(Alist):
  (visited,TE) = ({},[])
  infinity = 1 + max([d for i in Alist
                         for v,d in Alist[i]])
  for i in Alist:
    visited[i] = False

  mindist = infinity

  for i in Alist:
    for v,d in Alist[i]:
      if d < mindist:
        (mindist,nextv,currv) = (d,v,i)
  visited[currv] = True

  flag = True
  while flag:
    mindist = infinity
    nextv = None
    for i in visited:
      if visited[i]:
        for v,d in Alist[i]:
          if (not visited[v] and d < mindist):
            (mindist,nextv,currv) = (d,v,i)
    if (nextv!=None):
      visited[nextv] = True
      TE.append((currv,nextv))
    else:
      break
  return TE
prims_algo(Alist)

[(1, 3), (1, 0), (1, 2), (2, 4)]

In [ ]:
#Prim's Algo - Optimised
def prim_algo2(Alist):
  infinity = 1 + max([d for u in Alist.keys()
                    for (v,d) in Alist[u]])
  (visited,distance,nbr) = ({},{},{})
  for v in Alist.keys():
    (visited[v], distance[v], nbr[v]) = (False,infinity,-1)
  visited[0] = True
  for (v,d) in Alist[0]:
    (distance[v],nbr[v]) = (d,0)

  for i in range (1, len(Alist.keys())):
    nextd = min([distance[v] for v in Alist.keys()
                            if not visited[v]])
    nextvlist = [v for v in Alist.keys()
                    if (not visited[v] and distance[v] == nextd)]
    if nextvlist == 0:
      break
    nextv = min(nextvlist)
    visited[nextv] = True
    for (v,d) in Alist[nextv]:
      if not visited[v]:
        (distance[v],nbr[v]) = (min(distance[v],d),nextv)
  return(nbr)
prim_algo2(Alist)


{0: -1, 1: 0, 2: 1, 3: 1, 4: 2}

##Minimum Cost Spanning Tree - Kruskal's Algorithm - O(n^2)##

Strategy
1. Iteratively add the edge with the lowest cost to a Tree

In [ ]:
def kruskal_algo(Alist):
  (edges,component,TE) = ([],{},[])
  for u in Alist.keys():
    edges.extend([(d,u,v) for v,d in Alist[u]])
    component[u] = u
  edges.sort()

  for (d,u,v) in edges:
    # Checks if the two vertices belong to the same component. Further process only if they are not
    if component[u] != component[v]:
      TE.append((u,v))
      c = component[u]
      # Loop to transfer all vertices connected to component u to component v
      for w in Alist.keys():
        if component[w] == c:
          component[w] = component[v]
  return TE

kruskal_algo(Alist)


[(0, 1), (0, 3), (3, 4), (2, 4)]

##All Pairs Shortest Path - Floyd Warshall Algorithm##

Strategy
1. Start with an adjacency matrix with directed connections and their weights - W
2. Requirement is to create a stack of matrices SP, with each item in the stack representing the shortest path using a particular vertex until that point. E.g SP2 represents shortest path to every vertex using 0 and 1.
3. The shortest path is computed as the minimum of the already existing weight from i to j or the sum of the weights from i to k and k to j.
4. The result is a stack of matrices that shows the shortest path between any pair of vertices

In [ ]:
def floydwarshall(Amat):
  (rows, cols,x) = Amat.shape
  infinity = np.max(Amat)*rows*rows+1
  SP = np.zeros(shape=(rows, cols,cols+1))
  for i in range(rows):
    for j in range(cols):
      SP[i,j,0] = infinity

  for i in range(rows):
    for j in range(cols):
      if (Amat[i,j,0] == 1):
        SP[i,j,0] = Amat[i,j,1]

  for k in range(1,cols+1):
    for i in range(rows):
      for j in range(cols):
        SP[i,j,k] = min(SP[i,j,k-1],SP[i,k-1,k-1] + SP[k-1,j,k-1])

  print (SP[0])

floydwarshall(Amat)



[[641. 641. 641. 641. 641. 641. 641. 641. 641.]
 [ 10.  10.  10.  10.  10.  10.  10.  10.   5.]
 [641. 641. 641. 641. 641. 641.  10.  10.   5.]
 [641. 641. 641. 641. 641. 641.  11.  11.   6.]
 [641. 641. 641. 641. 641. 641.  14.  14.   9.]
 [641. 641.  12.  12.  12.  12.  12.  12.   7.]
 [641. 641. 641. 641. 641. 641. 641. 641.   9.]
 [  8.   8.   8.   8.   8.   8.   8.   8.   8.]]


In [ ]:
import numpy as np
def floydwarshall(Alist):
  (rows, cols,x) = (len(Alist),len(Alist),0)
  max = 0
  for i in Alist:
    for j in Alist[i]:
      if (abs(j[1]) > max):
        max = abs(j[1])
  infinity = abs(max) * rows*rows+1

  SP = np.zeros(shape=(rows, cols,cols+1))
  for i in range(rows):
    for j in range(cols):
      SP[i,j,0] = infinity

  for i in Alist:
    for j in Alist[i]:
       SP[i,j[0],0] = j[1]

  for k in range(1,cols+1):
    for i in range(rows):
      for j in range(cols):
        SP[i,j,k] = min(SP[i,j,k-1],SP[i,k-1,k-1] + SP[k-1,j,k-1])

  print (SP)

floydwarshall(Alist)

[[[641. 641. 641. 641. 641. 641. 641. 641. 641.]
  [ 10.  10.  10.  10.  10.  10.  10.  10.   5.]
  [641. 641. 641. 641. 641. 641.  10.  10.   5.]
  [641. 641. 641. 641. 641. 641.  11.  11.   6.]
  [641. 641. 641. 641. 641. 641.  14.  14.   9.]
  [641. 641.  12.  12.  12.  12.  12.  12.   7.]
  [641. 641. 641. 641. 641. 641. 641. 641.   9.]
  [  8.   8.   8.   8.   8.   8.   8.   8.   8.]]

 [[641. 641. 641. 641. 641. 641. 641. 641. 641.]
  [641. 641. 641. 641. 641. 641.   1.   1.   1.]
  [641. 641. 641. 641. 641. 641.   0.   0.   0.]
  [641. 641. 641. 641. 641. 641.   1.   1.   1.]
  [641. 641. 641. 641. 641. 641.   4.   4.   4.]
  [  2.   2.   2.   2.   2.   2.   2.   2.   2.]
  [641. 641. 641. 641. 641. 641. 641. 641. 641.]
  [641. 641. 641. 641. 641. 641. 641. 641. 641.]]

 [[641. 641. 641. 641. 641. 641. 641. 641. 641.]
  [  1.   1.   1.   1.   1.   1.   1.   1.   1.]
  [641. 641. 641. 641. 641. 641.   1.   1.   1.]
  [  1.   1.   1.   1.   1.   1.   1.   1.   1.]
  [641. 641. 641

In [ ]:
dedges = [(0,1,10),(0,2,50),(0,3,300),(5,6,45),(2,1,30),(6,4,37),(1,6,65),(2,5,76),(1,3,40),(3,4,60),(2,4,20)]
edges = dedges + [(j,i,w) for i,j,w in dedges]
dim = 7
print (edges)

[(0, 1, 10), (0, 2, 50), (0, 3, 300), (5, 6, 45), (2, 1, 30), (6, 4, 37), (1, 6, 65), (2, 5, 76), (1, 3, 40), (3, 4, 60), (2, 4, 20), (1, 0, 10), (2, 0, 50), (3, 0, 300), (6, 5, 45), (1, 2, 30), (4, 6, 37), (6, 1, 65), (5, 2, 76), (3, 1, 40), (4, 3, 60), (4, 2, 20)]


##Bellman Ford along with the Shortest Path taken##

In [ ]:
# Bellman-Ford using Adjacency List
# Call the function with Alist and source
# Find infinity
# Initialise distance with infinity (visited not required to be kept track of in this algorithm)
# set distance of the source to zero
# Iteratively

def bellman_ford(Alist,s,z):
# Infinity = the max value among all the the cells * rows + 1
  max = 0
  for i in Alist:
    for j in Alist[i]:
      if (j[1]) > max:
        max = (j[1])
  infinity = max*len(Alist)+1
# For each vertex in Amat
# set visited = false and distance = infinity
  (distance,path) = ({},{})
  for i in Alist:
    distance[i] = infinity
    path[i] = []
# Set distance for source vertex = 0
  distance[s] = 0
  path[s].append(s)
  for i in Alist:
    for u in Alist:
      path[s] + [u]
      for v,d in Alist[u]:
        if (distance[v] > distance[u] + d):
          path[v] = path[u] + [v]
        distance[v] = min(distance[v],distance[u] + d)
  #print (path)
  return (distance[z], path[z])

def min_cost_walk(Alist,S,D,V):
  dist, path = (bellman_ford(Alist,S,V))
  dist1, path1 = (bellman_ford(Alist,V,D))
  return (dist+dist1,path+path1[1:])

print (min_cost_walk(Alist,0,4,5))

(198, [0, 1, 2, 5, 6, 4])


In [ ]:
def prime_bad(n):
  if n < 2:
    return False
  for i in range (2, n//2):
    print ('here')
    if n%i == 0:
      return False
  return True

print (prime_bad(6))

here
False
